import { Organization } from '@/shared/types/fighter';

export const ORGANIZATIONS: Organization[] = ['UFC', 'ONE', 'PFL', 'Bellator'];
export const STANCES = ['Orthodox', 'Southpaw', 'Switch'] as const;
export const GENDERS = ['Male', 'Female'] as const;

export type FormData = {
  firstName: string;
  lastName: string;
  nickname: string;
  dateOfBirth: string;
  nationality: string;
  gender: 'Male' | 'Female';
  weightClass: import('@/shared/types/fighter').WeightClass;
  stance: 'Orthodox' | 'Southpaw' | 'Switch';
  organization: Organization;
  gym: string;
  headCoach: string;
  team: string;
  age: number;
  height: string;
  heightInches: number;
  reach: string;
  reachInches: number;
  legReach: string;
  legReachInches: number;
  weight: number;
  wins: number;
  losses: number;
  draws: number;
  noContests: number;
  koWins: number;
  tkoWins: number;
  submissionWins: number;
  decisionWins: number;
  finishRate: number;
  strikeAccuracy: number;
  strikeDefense: number;
  takedownAvg: number;
  takedownAccuracy: number;
  takedownDefense: number;
  strikesLandedPerMin: number;
  strikesAbsorbedPerMin: number;
  submissionAvg: number;
  lossesByKo: number;
  lossesBySubmission: number;
  lossesByDecision: number;
  longestWinStreak: number;
  fightingOutOf: string;
  rankGlobal: number;
  rankPromotion: number;
  isVerified: boolean;
};
