export const COUNTRIES = [
    { code: 'US', name: 'United States', flag: '🇺🇸' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
    { code: 'RU', name: 'Russia', flag: '🇷🇺' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪' },
    { code: 'FR', name: 'France', flag: '🇫🇷' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
    { code: 'PL', name: 'Poland', flag: '🇵🇱' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
    { code: 'CN', name: 'China', flag: '🇨🇳' },
    { code: 'IN', name: 'India', flag: '🇮🇳' },
    { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
    { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
    { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
    { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
    { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
    { code: 'AE', name: 'UAE', flag: '🇦🇪' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮' },
    { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
    { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
];

export const getCountryFlag = (countryName: string) => {
    return COUNTRIES.find(c => c.name === countryName)?.flag || '🏳️';
};
